name: Release Docker Image on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: mvn test

      - name: Extract tag name
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Tag = ${GITHUB_REF#refs/tags/}"

      - name: Build and package the app
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg APP_VERSION=${{ env.TAG_NAME }} -t ${{ secrets.DOCKER_USERNAME }}/store_app_be:${{ env.TAG_NAME }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/store_app_be:${TAG_NAME} ${{ secrets.DOCKER_USERNAME }}/store_app_be:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/store_app_be:${TAG_NAME}
          docker push ${{ secrets.DOCKER_USERNAME }}/store_app_be:latest
